Apple page clone
e71az/Apple-Clone pull request #1
Opened 2020-05-20 03:56 UTC by e71az

In this project I built a clone webpage of the Apple webpage. I had to create the article required applying grids and background images, I also used flex box and grid.

2020-05-20 05:40 UTC, sumancrest0001 commented on index.html
> +          <span></span>
**STATUS: REQUIRED CHANGES
Hello @e71az,**
It looks almost perfect to me and most of the requirements are implemented but there are a couple of minor changes required. Let's fix them.
[Required] we have to add a link to each of the nav-items. [Link to the page](https://web.archive.org/web/20140301004610/http://www.apple.com/)

2020-05-20 05:41 UTC, sumancrest0001 commented on normalize.css
> +
[Required] Let's remove all the comments. If you want to reference them back then use git history.

2020-05-20 05:47 UTC, sumancrest0001 reviewed
[Required] the image-logo at the footer should be on the same line as other items. Currently, it is on another line. Have a look :point_down: 
![Screenshot from 2020-05-20 11-27-28](https://user-images.githubusercontent.com/37747619/82409450-81fb0780-9a8d-11ea-9dbe-4d2e942613bb.png)

It should be :point_down: 
![Screenshot from 2020-05-20 11-27-41](https://user-images.githubusercontent.com/37747619/82409463-8b846f80-9a8d-11ea-8640-edf15aaed92d.png)

2020-05-20 05:51 UTC, sumancrest0001 requested changes
[IMPORTANT] Stickler is not passing, I think there is some problem with it. Let's fix.

After making the requested changes, request for another review.
**if you need help or have queries regarding the review, DM me on slack Suman Shrestha**
**Happy coding !!!**

2020-05-21 01:44 UTC, trekab approved these changes
# Approved!
Hi @e71az, you have done an impressive job on this project! :clap:  You may merge to master.
_All the best on your next projects!_ :wink:
__Treasure Kabareebe__

2020-05-21 05:21 UTC, merged